### ISSUE TITLE
How can one make null.JsonRawMessage

### ISSUE THREAD

**Issue by hllhll** [guregu/null#12]
Purpose: to allow cases where field it's value does not exist inside an wrapping object to be sent to the server as NULL JSON/JSONB Value (where structure type is json.RawMessage)

If someone could implement it it would be even better.

**Comment by guregu** [comment]
Hello, I don't have the luxury of Postgres or fancy new MySQL versions so I don't really know how their JSON encoding works. I'm totally okay with supporting it somehow though.

**Comment by lunemec** [comment]
I think the sql driver would need to support his first.

**Comment by guregu** [comment]
I see. In that case it's beyond the scope of this package.
