### ISSUE TITLE
IsZero string.

### ISSUE THREAD

**Issue by canhlinh** [guregu/null#21]
How can we check `null.String value` where is null or where is empty ?

I see the function `IsZero` work not as expected.

**Comment by guregu** [comment]
This is pretty confusing, but `IsZero` was added in hope that the official json library would change and allow us to specify arbitrary methods for `omitempty` with it. There's a link to a now-closed bug in the README. So `null.String`'s `IsZero()` acts like `*string` and considers itself "zero" only when it's null. 

So you could do something like `empty := !str.Valid || str.String == ""`. Or you could use the `zero` subpackage which [does that for you](https://github.com/guregu/null/blob/41961cea0328defc5f95c1c473f89ebf0d1813f6/zero/string.go#L102).
