### ISSUE TITLE
Add support for the time.Duration type

### ISSUE THREAD

**Issue by njern** [guregu/null#26]
Like this library, very clean & nice to use.

Would you be interested in adding support for / accepting a PR with an implementation of `null.Duration` ?

**Comment by guregu** [comment]
Thanks!
What SQL types would it match up with? If it works with major DBs like MySQL/Postgres/SQLite then I would be interested in adding it.

**Comment by guregu** [comment]
Just a warning though in general I intend to support only the types that driver.Value can be. https://golang.org/pkg/database/sql/driver/#Value

However, if we can demonstrate that this would be widely compatible then it might be worth adding. It may be a better idea to add it to https://github.com/guregu/toki or make a new package.
Either way please feel free to fork this library or toki and I'll take a look at it.

I appreciate that you made an issue first 👍

**Comment by njern** [comment]
I can't speak for MySQL but the corresponding type in PostgreSQL is `interval`. I think it's a fairly normal data type to store in databases, either as a field by itself or then as the result from a +/- operation between two timestamps.

I looked at toki and still think this package could be a better fit but happy to hear your thoughts.

**Comment by guregu** [comment]
Alright, feel free to submit a patch here!

**Comment by guregu** [comment]
Sorry for waffling about this, but I've decided to limit the package to the types supported by the sql driver.
