### ISSUE TITLE
Support for uint

### ISSUE THREAD

**Issue by DenLilleMand** [guregu/null#40]
I realize that the db driver doesn't support `uint` as a type and that javascript only have the number type. Basically meaning a rather small performance hit because of the conversion we would need to do, not to mention the complications with overflow. 

But i still think in some of the structs we have it would make sense to have a `null.Uint` just for cosmetic purposes and to enforce correct types at the point of storage to avoid errors. Would a PR with `uint` type(s) be accepted?

**Comment by guregu** [comment]
I can see how this would be useful but I'm going to limit the scope of this library to the types the DB drivers support.
