### ISSUE TITLE
Release v4

### ISSUE THREAD

**Issue by guregu** [guregu/null#48]
I'd like to work towards releasing a new version.

### v3 stuff
* [x] Merge #36 because it's backwards compatible, need to add `zero` support first.
### v4 stuff
* [x] Fix #47 (backwards incompatible) 
* [x] Take the opportunity to get rid of some cruft? If we drop support for marshaling from sql.NullXXX **JSON objects** (as in https://github.com/guregu/null/blob/80515d440932108546bcade467bb7d6968e812e2/int.go#L70-L71) we can speed up the library a bit and avoid having to unmarshal into `interface{}` first. I doubt many people use this anyway.

**Comment by limoli** [comment]
Waiting for this amazing version :)

**Comment by guregu** [comment]
Done, sorry for the wait.
