### ISSUE TITLE
null.String composite literal uses unkeyed fields

### ISSUE THREAD

**Issue by Myskmadra** [guregu/null#52]
Hey,

I have a question. The null.String type does not have a key specified. Thus, govet as well as sonarqube give me the warning:

vendor/gopkg.in/guregu/null.v3.String composite literal uses unkeyed fields

for a struct using this type. I was wondering if it's possible to change that or if there is a fix for this?

**Comment by guregu** [comment]
Hello, this should have been fixed a while ago. Does it still happen? My `go vet` seems to be fine.

**Comment by Myskmadra** [comment]
I used a workaround. But if it is fixed, we can close this issue. Cheers, man!
