### ISSUE TITLE
Strings.StringFrom() passes Valid as true even if the string is empty

### ISSUE THREAD

**Issue by xfoxawy** [guregu/null#56]
example
```
StringFrom("")
``
value
```
sql.NullString{Value:"", Valid:true}
```
which is wrong

**Comment by guregu** [comment]
It’s not wrong, it’s intentional. Use the zero subpackage if you want this kind of behavior.

I noticed the documentation is kind of misleading though, “blank” should be changed to “null”.

**Comment by xfoxawy** [comment]
should I extract this behavior in new method then?

**Comment by guregu** [comment]
No need, this behavior is already implemented in this zero subpackage: https://godoc.org/github.com/guregu/null/zero#StringFrom
