### ISSUE TITLE
[Question] Is it possible to have SQL null values treated as null in Go but encode them to zero in JSON?

### ISSUE THREAD

**Issue by maxiride** [guregu/null#61]
From the documentation I understand that types are either fully treated as zero or null values in Go and JSON.

I am trying to understand if I can use null values in Go but have them encoded to zero in JSON.

**Comment by guregu** [comment]
The `zero` package types will marshal to zero values in JSON but null in SQL.
For example a blank `zero.String` will be considered null, and JSON marshal as `""`.

**Comment by maxiride** [comment]
> 
> 
> The `zero` package types will marshal to zero values in JSON but null in SQL.
> For example a blank `zero.String` will be considered null, and JSON marshal as `""`.

Sorry I must have made confusion in the phrasing but thanks for the clarification! 

---

By the way awesome package!
