### ISSUE TITLE
uint64 support

### ISSUE THREAD

**Issue by Fabio1988** [guregu/null#71]
Hey guys,

is it on purpose that this module can not support uint64 (bigint unsigned)? 

casting uint64 to int64 will cause a loss of the last bit. And therefore I would have wrong results in DB

```golang
type Thing struct {
  Id string `db:"id"`
  number null.Int `db:"name"`
```

Database has the schema: 
```sql
CREATE TABLE `thing` (
`id` varchar(25) NOT NULL,
`number` bigint unsigned DEFAULT NULL
)
```

Implemtation of [null.IntFrom](https://github.com/guregu/null/blob/21596e8e52a426a14cd73b22f6ffa4d31165302f/int.go#L30)

Is it sqlx not supporting it? How can I work around that?! :) 
related to: https://github.com/go-sql-driver/mysql/issues/715 ?

**Comment by guregu** [comment]
Hey. Yes, it's related to the issue you linked. Basically, Go's sql package does not guarantee support of uint64.
See: [here](https://github.com/guregu/null#can-you-add-support-for-other-types).

There is a fork of this package here that has a lot more types. I'd suggest checking that out if you need them: https://github.com/volatiletech/null

**Comment by Fabio1988** [comment]
Thank you :)
