### ISSUE TITLE
Decoding large integers.

### ISSUE THREAD

**Issue by juandiegopalomino** [guregu/null#8]
Hi guregu,
My teammates and I really like your library, as it has helped us a lot when going from JSON to go structs to databases (thank you!). One small issue we found is unmarshalling large numbers from JSON. Right now, because there is only one number type in Javascript, integers in JSON that are large enough are decoded in scientific notation. Because of this, these numbers cannot be unmarshalled into integer types, in particular your null.Int and zero.Int types. I was wondering if you had any thoughts on the issue. 

If you're interested, I've already written an implementation that passes all of the tests, if you want to take a look.

**Comment by guregu** [comment]
Hello, thank you for the kind words.

null.Float/zero.Float and would be the closest thing to Javascript numbers, and should support scientific notation. 

Just making sure: are you numbers within the range of Go's int64 and just happen to be in scientific notation, or are your numbers larger than int64 can handle?

Go's `encoding/json` package dislikes scientific notation in any integer, even if it's a small number: http://play.golang.org/p/0uDEOPdl8U
Seems like a bug to me, to be honest...

Did you add support for something like `big.Int`? 
Either way, I would be happy to include your code.

**Comment by juandiegopalomino** [comment]
Hi guregu,
So upon further investigation, it seems that my issue stemmed from first unmarshalling the json to a map[string]interface{}, which automatically writes numbers in scientific notation. Sorry about that. The solution I wrote was basically, if unmarshalling to an int64 failed, then try unmarshalling it to a float64, and using that number if it's a valid int64 (I check that it doesn't have decimals, and is within the int64 range). If you're still interested, I'll be happy to supply you the small fix (it's only 10 lines). Thank you for your time, and have a nice day!

**Comment by guregu** [comment]
I'll keep things as-is for now, but thanks for the input.
